spring:
  h2:
    console:
      enabled: true
      path: /h2
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:pessoadb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
server:
  port: 8090